services:
  db:
    image: mysql:8.0
    container_name: mysql_db_dev
    #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend_dev
    #restart: unless-stopped
    #depends_on:
    #s  - backend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    environment:
      - VITE_API_URL=http://localhost:8080

volumes:
  mysql_data_dev:
